/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import au.com.bytecode.opencsv.CSVReader;
import dao.ArquivoDao;
import dao.EmpresaDao;
import entidade.Arquivo;
import entidade.Empresa;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.MidiDevice;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Giliard
 */
public class ImportaCsv extends javax.swing.JFrame {

    /**
     * Creates new form ImportaCsv
     */
    JFileChooser jfc;
    String log;
    EmpresaDao empresaDao = new EmpresaDao();
    ArquivoDao arquivoDao = new ArquivoDao();
    DefaultComboBoxModel combomodel;
    private DefaultTableModel model;

    public ImportaCsv() {
        initComponents();
        carregaComboBoxEmpresa();
        initTela();
        this.jProgressBar1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        TxtArquivo = new javax.swing.JTextField();
        btArquivo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbxEmpresa = new javax.swing.JComboBox<>();
        btProcessar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        TxtArquivo.setEditable(false);
        TxtArquivo.setName("txtArquivo"); // NOI18N

        btArquivo.setText("Selecionar Arquivo");
        btArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoSelecionarArquivo(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        jButton3.setText("Importar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tasks.png"))); // NOI18N
        jButton1.setText("Log");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxEmpresa.setToolTipText("");
        cbxEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btProcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save-icon.png"))); // NOI18N
        btProcessar.setText("Procesar");
        btProcessar.setEnabled(false);
        btProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btProcessar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                    .addComponent(cbxEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btArquivo))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btArquivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cbxEmpresa.getAccessibleContext().setAccessibleName("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Importar Arquivo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Data da Importacao", "nome", "Local", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (validacao()) {
            this.jProgressBar1.setVisible(true);
            new Thread(new BarraProcesso(this.jProgressBar1, 1)).start();
            String razaoSocial = (String) cbxEmpresa.getModel().getSelectedItem();

            Empresa empresaSelecionada = empresaDao.pesquisaRzSocial(razaoSocial);
            Arquivo arquivo = new Arquivo();
            arquivo.setDataImportacao(new Date());
            arquivo.setStatus("Pendente");
            arquivo.setEmpresa(empresaSelecionada);
            arquivo.setNOME(jfc.getSelectedFile().getAbsolutePath());
            arquivoDao.persist(arquivo);
            initTela();

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBotaoSelecionarArquivo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoSelecionarArquivo
        jfc = new JFileChooser("c:/");
        int cmd = jfc.showOpenDialog(this);
        TxtArquivo.setText(jfc.getSelectedFile().getPath());

        if (cmd != JFileChooser.APPROVE_OPTION) {
            return;
        }
    }//GEN-LAST:event_jBotaoSelecionarArquivo

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        habilitaBotaoProcessar();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame jp = new JFrame();
        javax.swing.JTextArea txtLog = new JTextArea();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcessarActionPerformed
        processaArquivo();
    }//GEN-LAST:event_btProcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportaCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportaCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportaCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportaCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportaCsv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField TxtArquivo;
    javax.swing.JButton btArquivo;
    javax.swing.JButton btProcessar;
    javax.swing.JComboBox<String> cbxEmpresa;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton3;
    javax.swing.JLabel jLabel1;
    javax.swing.JPanel jPanel1;
    javax.swing.JProgressBar jProgressBar1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void carregaComboBoxEmpresa() {

        combomodel = (DefaultComboBoxModel) cbxEmpresa.getModel();
        combomodel.removeAllElements();
        combomodel.addElement("Selecione uma empresa");
        List<Empresa> empresas = (List<Empresa>) empresaDao.findAll();

        for (Empresa empresa : empresas) {

            combomodel.addElement(empresa.getRazaoSocial());

        }
        System.out.println("" + combomodel.getSize());
        cbxEmpresa.setModel(combomodel);
        //cbxEmpresa.setName(comb);

    }

    private Boolean validacao() {

        boolean ok = true;
        if (this.TxtArquivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não foi escolido nehum aruqivo.");
            ok = false;
        }
        if (this.cbxEmpresa.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Favor selecionar a Empresa.");
            ok = false;
        }
        return ok;
    }

    public void tableModel() {
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);

        model = (DefaultTableModel) this.jTable1.getModel();
        model.setNumRows(0);
    }

    public void cargarTabla() {

        List<Arquivo> lista = (List<Arquivo>) arquivoDao.findAll();
        for (Arquivo arquivo : lista) {
            model.addRow(new Object[]{
                arquivo.getId(), arquivo.getDataImportacao(),
                arquivo.getEmpresa().getRazaoSocial(), arquivo.getNOME(),
                arquivo.getStatus()
            });
        }
    }

    private void limpaCampo() {
        this.TxtArquivo.setText(null);
        this.cbxEmpresa.setSelectedIndex(0);
        this.btProcessar.setEnabled(false);

    }

    private void initTela() {
        tableModel();
        cargarTabla();
        limpaCampo();
    }

    private void habilitaBotaoProcessar() {
        btProcessar.setEnabled(true);
    }

    private void processaArquivo() {
        boolean erro = false;
        CSVReader reader;
        int selectedRow = this.jTable1.getSelectedRow();
        Object valueAt = model.getValueAt(selectedRow, 0);
        Integer idArt = Integer.parseInt(valueAt.toString());
        Arquivo arquivo = arquivoDao.getById(idArt);
        if (arquivo == null) {
            JOptionPane.showMessageDialog(null, "Registro inexistente");
        }

        try {

            System.out.println("Importando arquivo da empresa " + arquivo.getEmpresa().getRazaoSocial());
            reader = new CSVReader(new FileReader(arquivo.getNOME()));

            String[] nextLine;
            while ((nextLine = reader.readNext()) != null) {
                // nextLine[] is an array of values from the line
                log = nextLine[0] + " - " + nextLine[1] + " - " + nextLine[2] + " - " + nextLine[3] + " - " + nextLine[4] + "\\n";
                System.out.println(nextLine[0] + " - " + nextLine[1] + " - " + nextLine[2] + " - " + nextLine[3] + " - " + nextLine[4]);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ImportaCsv.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ImportaCsv.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!erro) {
            arquivo.setStatus("Importado");
            arquivoDao.merge(arquivo);
            initTela();
            JOptionPane.showMessageDialog(null, "Arquivo processado com Sucesso!.","Importacao",1);
                  
        }
    }

}
